Description:
    model_name: exp2_unconstrained_nov30

general: 
    use_deterministic_algorithms: False
    batch_size: 4
    device: 'cpu'
    gpu : 0
    save_path : ./Out/example_naturalistic_unconstrained
    save_output: [phosphenes, stimulation, reconstruction]
    
simulator:
    base_config: ./viseon-dynaphos_model_parameters/Simulator Config/params.yaml
    use_threshold: False
    phosphene_map: ./viseon-dynaphos_model_parameters/Simulator Config/DefaultCoordinateMap_1000_phosphenes.pickle
    
e2e_models:
    model_architecture: end-to-end-autoencoder # choose from end-to-end-autoencoder, zhao-autoencoder
    in_channels: 1
    n_electrodes: 1000
    output_scaling: 128.0e-6
    output_steps: None # unconstrained output
    out_channels: 1
    encoder_out_activation: relu
    decoder_out_activation: sigmoid

optimization:
    learning_rate : 0.0005
    epochs : 16
    trainstats_per_epoch : 24
    validations_per_epoch: 8
    early_stop_criterium : 15

training_pipeline:
    pipeline: unconstrained-image-autoencoder
    regularization_weight: 0.5  # relative weight for enforcing interpretable (supervised) phosphene encodings
    

dataset:
    dataset: MNIST
    data_directory : /Users/maximilianharl/Dropbox/001_university/008_ETH_UZH/003.Semester/IDB402/lab/REPOS/trial_2/viseon/_Datasets/Characters/
    load_preprocessed: False # for the ADE50k dataset:
    sequence_length: 5 # for the BouncingMNIST dataset:
    mode: recon # for the BouncingMNIST dataset:
    flip_vertical: False # for Characters dataset
    flip_horizontal: False # for Characters dataset
    
    


    
    


