Description:
    model_name: mvh_IDB402_tryouts

general: 
    use_deterministic_algorithms: False
    batch_size: 4
    device: 'cpu'
    gpu : 0
    save_path : ./Out/spike_SEE
    save_output: [phosphenes, stimulation, reconstruction]
    
simulator:
    base_config: ./viseon-dynaphos_model_parameters/Simulator Config/params.yaml
    use_threshold: False
    phosphene_map: ./viseon-dynaphos_model_parameters/Simulator Config/DefaultCoordinateMap_1000_phosphenes.pickle
    
e2e_models:
    model_architecture: SpikingMVH-autoencoder # SpikingMVH-autoencoder # SpikingMVH-autoencoder # choose from end-to-end-autoencoder, zhao-autoencoder, SpikeSEE-autoencoder
    in_channels: 1
    n_electrodes: 1000
    output_scaling: 128.0e-6
    output_steps: None # unconstrained output
    out_channels: 1
    encoder_out_activation: relu
    decoder_out_activation: sigmoid
    num_steps: 25

optimization:
    learning_rate : 0.0005
    epochs : 5 # previous 16
    trainstats_per_epoch : 6 # previous 24
    validations_per_epoch: 2 # previous 8
    early_stop_criterium : 5 # previous 15

training_pipeline:
    pipeline: MVH-spiking # MVH-spiking # MVH-image-autoencoder
    regularization_weight: 0.5  # relative weight for enforcing interpretable (supervised) phosphene encodings
    

dataset:
    dataset: MNIST
    data_directory : /Users/maximilianharl/Dropbox/001_university/008_ETH_UZH/003.Semester/IDB402/lab/REPOS/trial_2/viseon/_Datasets/
    # data_directory: /Users/maximilianharl/Dropbox/001_university/008_ETH_UZH/003.Semester/IDB402/lab/REPOS/trial_2/viseon/_Datasets/Characters/
    load_preprocessed: False # for the ADE50k dataset:
    sequence_length: 5 # for the BouncingMNIST dataset:
    mode: recon # for the BouncingMNIST dataset:
    flip_vertical: False # for Characters dataset
    flip_horizontal: False # for Characters dataset
    subset: 1000
    
    


    
    


